#@ load("@ytt:data", "data")
#@ def api_version_shortname(ep):
#@   return ep.api_version_shortname
#@ end

#@ def route_paths(ep):
#@   return ep.route_paths
#@ end
---
services:
#@ for/end ep in data.values.end_point:
  - name: #@ api_version_shortname(ep)
    url: #@ data.values.host.baseurl
    plugins:
    - name: oneapi
      config:
        api_version_shortname: #@ api_version_shortname(ep)
        authentication:
          authentication_type: apikey
          apikey:
            header_name: "x-api-key"
        upstream_auth:
          jwt:
            hs256_sign_secret: am9vd2lyc2FubWltcmFkbGRvam9vd2lyc2FubWltcmFkbGRv
            header_name: x-claims
            claims:
              - sub
              - client_id
              - scope
              - application_id
              - custom_client_identification
              - access_token
    routes:
    - name: #@ api_version_shortname(ep)
      paths: 
      -  #@ route_paths(ep)      
      strip_path: false